# Generated by Django 4.2.3 on 2023-09-22 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
